### ISSUE TITLE
Minimum computing resources requirement and smaller setup

### ISSUE THREAD

**Issue by ogbautista** [snwagh/ponytail-public#1]
Hello Sameer,
Certainly the answer to these questions may help others:
What are the minimum CPU and RAM requirements? also, virtual memory would be enough? or a at least a portion of the total RAM required by the program?
Also, for testing purposes, can I easily reduce the size of a modulo so that it can run this with less resources? for instance (just an idea) a modulus 32768 could be set to a lower value?
Thanks!

**Comment by snwagh** [comment]
Indeed, the code is fairly memory heavy, particularly with the hoisting optimization. Loosely speaking, the memory footprint will be between 50-70GB for the experiments in the paper. I don't think virtual memory smaller than this would work. 

As far as I understand, there should not be any harm in reducing the modulo to reduce the resource demands, the only consideration would be checking the HE side of the doing it. 

I have pasted a valid run below for a 128x128 matrix multiplication (for command line arguments 16,1,1,1,1,128)

> log p = 128
 log q = 656
592328157823369217
1142105516156846081
912962469254922241
959107683623436289
665898899883360257
594876053095383041
1152847380137902081
588677270534225921
1047482905341591553
1107187661831274497
1128384093308846081
718711851254218753
HACK: add 2 To deal with large prime modulus ... HACK: add 2 To deal with large prime modulus ... HACK: add 2 To deal with large prime modulus ... HACK: add 2 To deal with large prime modulus ... HACK: add 2 To deal with large prime modulus ... HACK: add 2 To deal with large prime modulus ... HACK: add 2 To deal with large prime modulus ... HACK: add 2 To deal with large prime modulus ... HACK: add 2 To deal with large prime modulus ... HACK: add 2 To deal with large prime modulus ... HACK: add 2 To deal with large prime modulus ... HACK: add 2 To deal with large prime modulus ... /
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 32768
|   coeff_modulus size: 715 (60 + 60 + 60 + 60 + 60 + 60 + 60 + 60 + 60 + 60 + 60 + 60) bits
|   plain_modulus: 786433
\
Actual plain modulus 229804075793985810840703631710053203969
\--------------------------------------------
KeyGen time: 		82543 milliseconds
\--------------------------------------------
16 threads created
\--------------------------------------------
Enc(A0),Enc(B0) time: 		382 milliseconds
\--------------------------------------------
> Key copy time: 		6452 milliseconds
Memory Usage: 			49.7628(GB)
============================================
USing hoisting with Large P: masking vectors gen
> Mask Generation time: 		13959 milliseconds
Memory Usage: 			50.7636(GB)
============================================
Got here: k1 <= k3 
> Gen(E(A)) time: 		2765 milliseconds
Memory Usage: 			55.9824(GB)
============================================
> START Acts(all) + Bcts(0-col) ... 
Gen(E(B0)) time: 		1121 milliseconds
Memory Usage: 			56.0118(GB)
\------------------------
E(A) * E(B0) time: 		2696 milliseconds
Memory Usage: 			58.4815(GB)
\-----------------------------------
> total gen(B) time: 		1121 milliseconds
> total mult time: 		2696 milliseconds
\--------------------------------------------
Total time (selection=1): 	27001 milliseconds
\--------------------------------------------
noise budget (needs to be positive integer for correct decryption =  237
ok? 1
